Composite trainer
NVlabs/tiny-cuda-nn pull request #157
Opened 2022-09-26 08:36 UTC by Solonets

Hi once again and thank you for the great work. I was working on a project with your awesome lib and had a use case where I needed to optimize different parameters with different optimizers. Your yourself seem to see a point in this for example when training separately weights of the network with complex optimizers and primitive encodings (i.e frequency) with more trivial optimizers. You also seem to be applying different regularizers to different weights of the net, which you had to implement in many solvers. 

I went ahead and implemented a composite trainer which just runs several trainers, I hope it could be helpful.

2022-09-26 15:09 UTC, Solonets commented
@Tom94 I see there is a problem with the custom_weight() method. But I think I can fix it if you think it is worth it.

2022-10-03 07:03 UTC, Tom94 requested changes
This is great, thank you! See my review in the comments.

2022-10-03 07:03 UTC, Tom94 commented on include/tiny-cuda-nn/optimizers/composite.h
> +    return {{"nested", nested}};
Learning rate is missing here.

2022-10-03 07:03 UTC, Tom94 commented on include/tiny-cuda-nn/optimizers/composite.h
> +    update_hyperparams(params);
Missing `set_learning_rate` call

2022-10-03 07:03 UTC, Tom94 commented on include/tiny-cuda-nn/optimizers/composite.h
> +      learning_rate_scale = params["learning_rate_scale"];
Use `set_learning_rate` instead

2022-10-03 07:03 UTC, Tom94 commented on include/tiny-cuda-nn/optimizers/composite.h
> +    learning_rate_scale = data["learning_rate_scale"];
Use `set_learning_rate` instead

2022-10-04 11:58 UTC, Solonets commented on README.md
> +| Composite | `include/tiny-cuda-nn/optimizers/composite.h` | Allows using several optimizers on different parameters
it wasn't ordered before, I would assume you have 3 most common on the top, and then the rest in the alphabetical order?

2022-10-04 12:00 UTC, Tom94 commented on include/tiny-cuda-nn/optimizer.h
> +	virtual uint32_t num_nesting() const {
That's a great idea!

2022-10-04 13:03 UTC, Solonets commented on include/tiny-cuda-nn/optimizers/composite.h
> +std::vector<std::pair<uint32_t, uint32_t>> slice_weights(std::vector<std::pair<uint32_t, uint32_t>> object_layer_size,
Do you have any clang-format style of file that you follow?

2022-10-11 06:49 UTC, Tom94 commented
Hi, thank you very much for making adjustments! I just wanted to let you know I haven't forgotten / abandoned your PR. I plan to get to it again next week.

2022-10-18 07:05 UTC, merged

2022-10-18 07:08 UTC, Tom94 commented
Thanks again!